//! D44: generation entry point for the ts-rs bindings
//! (`cargo test -p muxsmith-core --features ts`). ts-rs's own
//! `#[ts(export)]` attribute, present on the 21 wire types (the 20 model
//! types plus `StructuredEdit`, D44/D49), generates one hidden `#[test]`
//! per type that writes `profile.ts` as a side effect of running this
//! binary. This file supplies the other committed artifact ts-rs cannot
//! produce on its own: `keywords.ts`. ts-rs exports types, not values, and
//! the four keyword domains are `pub const` value arrays, so a small
//! hand-written emitter writes them as TypeScript `as const` arrays (D44
//! `:592-611`). Both artifacts share one destination, `TS_RS_EXPORT_DIR`
//! (`.cargo/config.toml`).
#![cfg(feature = "ts")]

use std::path::Path;

use muxsmith_core::capability::{PropType, SETTABLE, matchable_properties, matchable_type};
use muxsmith_core::profile::model::{ChaptersCfg, FilenameCfg, SourceCfg, TitleCfg};

#[test]
fn emit_keywords_ts() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap();
    let mut out = String::from("// @generated by `cargo test -p muxsmith-core --features ts`\n");
    for (name, domain) in [
        ("FILENAME_KEYWORDS", FilenameCfg::KEYWORDS),
        ("SOURCE_KEYWORDS", SourceCfg::KEYWORDS),
        ("CHAPTERS_KEYWORDS", ChaptersCfg::KEYWORDS),
        ("TITLE_KEYWORDS", TitleCfg::KEYWORDS),
    ] {
        let items = domain
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("export const {name} = [{items}] as const;\n"));
    }
    std::fs::write(Path::new(&dir).join("keywords.ts"), out).unwrap();
}

/// `PropType -> TS tag` is total over all four real variants: a fifth
/// `PropType` variant fails this match at build time rather than silently
/// falling through a wildcard arm (the house never-arm shape, D46).
fn scalar_tag(t: PropType) -> &'static str {
    match t {
        PropType::String => "string",
        PropType::Boolean => "boolean",
        PropType::Integer => "integer",
        PropType::Float => "float",
    }
}

#[test]
fn emit_settables_ts() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap();
    let mut out = String::from("// @generated by `cargo test -p muxsmith-core --features ts`\n");
    out.push_str(
        "export type PropScalarType = \"boolean\" | \"integer\" | \"float\" | \"string\";\n",
    );

    out.push_str("export const SETTABLE_TYPES = {\n");
    for (name, ty, _option) in SETTABLE {
        out.push_str(&format!("  \"{name}\": \"{}\",\n", scalar_tag(*ty)));
    }
    out.push_str("} as const satisfies Record<string, PropScalarType>;\n");

    out.push_str("export const MATCHABLE_TYPES = {\n");
    for (name, ty) in matchable_properties() {
        out.push_str(&format!("  \"{name}\": \"{}\",\n", scalar_tag(*ty)));
    }
    out.push_str(&format!(
        "  \"codec_kind\": \"{}\",\n",
        scalar_tag(matchable_type("codec_kind").unwrap())
    ));
    out.push_str("} as const satisfies Record<string, PropScalarType>;\n");

    std::fs::write(Path::new(&dir).join("settables.ts"), out).unwrap();
}
