//! D44: generation entry point for the ts-rs bindings
//! (`cargo test -p muxsmith-core --features ts`). ts-rs's own
//! `#[ts(export)]` attribute, present on the 21 wire types (the 20 model
//! types plus `StructuredEdit`, D44/D49), generates one hidden `#[test]`
//! per type that writes `profile.ts` as a side effect of running this
//! binary. This file supplies the other committed artifact ts-rs cannot
//! produce on its own: `keywords.ts`. ts-rs exports types, not values, and
//! the four keyword domains are `pub const` value arrays, so a small
//! hand-written emitter writes them as TypeScript `as const` arrays (D44
//! `:592-611`). Both artifacts share one destination, `TS_RS_EXPORT_DIR`
//! (`.cargo/config.toml`).
#![cfg(feature = "ts")]

use std::path::Path;

use muxsmith_core::profile::model::{ChaptersCfg, FilenameCfg, SourceCfg, TitleCfg};

#[test]
fn emit_keywords_ts() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap();
    let mut out = String::from("// @generated by `cargo test -p muxsmith-core --features ts`\n");
    for (name, domain) in [
        ("FILENAME_KEYWORDS", FilenameCfg::KEYWORDS),
        ("SOURCE_KEYWORDS", SourceCfg::KEYWORDS),
        ("CHAPTERS_KEYWORDS", ChaptersCfg::KEYWORDS),
        ("TITLE_KEYWORDS", TitleCfg::KEYWORDS),
    ] {
        let items = domain
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("export const {name} = [{items}] as const;\n"));
    }
    std::fs::write(Path::new(&dir).join("keywords.ts"), out).unwrap();
}
