// @generated by `cargo test -p muxsmith-core --features ts`
export const FILENAME_KEYWORDS = ["keep"] as const;
export const SOURCE_KEYWORDS = ["primary"] as const;
export const CHAPTERS_KEYWORDS = ["keep", "drop"] as const;
export const TITLE_KEYWORDS = ["keep", "clear"] as const;
