// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exactly one of `select` / `drop` / `add` must be set; enforced in
 * validate.rs (AttachmentRuleShape) so the parse error stays readable.
 */
export type AttachmentRule = { 
/**
 * Select (keep) attachments matching this expression over
 * `file_name`/`content_type`/`description` (spec 4.9).
 */
select?: MatchExpr | null, 
/**
 * Drop attachments matching this expression; same property set as
 * `select`.
 */
drop?: MatchExpr | null, 
/**
 * Add an external file as an attachment, located the same way as a
 * track's external source (spec 4.6, 4.9).
 */
add?: Locator | null, };

/**
 * Attachment handling (spec 4.9).
 */
export type AttachmentsCfg = { 
/**
 * Policy for attachments no `rules` entry selects. Defaults to `keep`:
 * deliberate asymmetry with tracks (unmatched tracks are always
 * dropped), since dropping fonts silently breaks ASS subtitle
 * rendering.
 */
unmatched?: KeepDrop, 
/**
 * Ordered select/drop/add rules (spec 4.9). Unlike track rules, not
 * uniqueness-constrained: a `select`/`drop` expression may match
 * several attachments (fonts come in sets); rules apply in list order,
 * first matching rule wins per attachment.
 */
rules?: Array<AttachmentRule>, };

/**
 * `chapters` value: keep, drop, or an external locator (spec 4.9).
 * `#[serde(untagged)]`, same variant-resolution rule as [`FilenameCfg`]/[`SourceCfg`].
 */
export type ChaptersCfg = ExternalBlock | string;

/**
 * `output.on_collision` policy (spec 4.8): applies to an existing rendered
 * output path and to two planned outputs rendering to the same path. Does
 * not override `SourceOverwrite` (output path equal to an input path),
 * which is always a hard error regardless of this policy (spec 5.2).
 */
export type CollisionPolicy = "error" | "skip" | "overwrite";

/**
 * Shared `{ external: ... }` block; standalone for the same
 * `deny_unknown_fields` reason as [`TemplateBlock`].
 */
export type ExternalBlock = { 
/**
 * The external locator (spec 4.6) resolved to find the donor file(s).
 */
external: Locator, };

/**
 * `output.filename` value: either a literal-mode template or the `keep`
 * keyword (spec 4.8). `#[serde(untagged)]`: matches whichever variant
 * deserializes first, so a bare string becomes `Keyword` and a
 * `{ template: ... }` map becomes `Template`.
 */
export type FilenameCfg = TemplateBlock | string;

/**
 * Primary-file selection and directory-walk options (spec 4.2).
 */
export type Input = { 
/**
 * Regex searched (not anchored) against each candidate file's
 * basename; the first match's span and capture groups become the
 * identifier (spec 3) and populate template fields (`{match}`,
 * `{g1}`, named groups).
 */
pattern: string, 
/**
 * Candidate file extensions, matched case-insensitively; not restricted
 * to MKV. Checked once per batch against the local `mkvmerge
 * --list-types` (spec 4.2): an entry absent from that list is still
 * used for matching (so a typo silently excludes candidates) but
 * raises `UnknownExtension`. Skipped, not raised, when the runtime
 * capability is unavailable.
 */
extensions: Array<string>, 
/**
 * Whether the source directory walk descends into subdirectories.
 * Defaults to `true`.
 */
recursive?: boolean, };

/**
 * Binary keep-or-drop toggle shared by `attachments.unmatched`,
 * `tags.global` and `tags.track` (spec 4.9).
 */
export type KeepDrop = "keep" | "drop";

/**
 * External file locator (spec 4.6): finds candidate donor files; the
 * owning rule's `match` then selects exactly one track inside the located
 * file. Uniqueness applies at both stages: two or more matching files is
 * `AmbiguousExternal`, two or more matching tracks inside the file is
 * `AmbiguousRule`.
 */
export type Locator = { 
/**
 * Directory to search, relative to the primary file's directory, or
 * absolute. A filesystem path; serialized as a plain string, so the
 * profile format is unchanged. Use forward slashes in profiles for
 * portability (Windows accepts them).
 */
path: string, 
/**
 * Whether the search descends into subdirectories of `path`. Defaults
 * to `false`, deliberately asymmetric with `input.recursive`
 * (default `true`).
 */
recursive?: boolean, 
/**
 * Candidate extensions, validated against `mkvmerge --list-types`
 * like `input.extensions`.
 */
extensions: Array<string>, 
/**
 * Sugar for `match_pattern: '{match}'`: the candidate's basename must
 * match the primary's identifier. Mutually exclusive with
 * `match_pattern` (`LocatorConflict` if both are set); the only valid
 * value is `true`.
 */
match_to_source?: boolean | null, 
/**
 * Regex-mode template (spec 4.7) the candidate's basename must match;
 * mutually exclusive with `match_to_source`.
 */
match_pattern?: string | null, 
/**
 * Whether `match_pattern` matching is case-sensitive. Defaults to
 * `false` (the rendered pattern is prefixed `(?i)`, spec 4.7).
 */
case_sensitive?: boolean, };

/**
 * One match expression: a conjunction of up to five parts, all present
 * parts must hold (spec 4.3). Evaluated against every track/attachment of
 * a resolved source; `any`/`not` recurse to arbitrary depth (typical
 * profiles stay flat).
 */
export type MatchExpr = { 
/**
 * Property -> value equality after normalization; case-sensitive for
 * strings (language values are normalized separately, spec 4.4).
 * Multiple entries in the map are AND'd.
 */
exact?: { [key in string]: Scalar } | null, 
/**
 * Property -> substring, case-insensitive containment; string
 * properties only ([`crate::capability::PropType::String`] required),
 * otherwise a config-time type error.
 */
substring?: { [key in string]: string } | null, 
/**
 * Property -> regex, taken as written (use `(?i)` for case-insensitive
 * matching); string properties only, same type-error rule as `substring`.
 */
regex?: { [key in string]: string } | null, 
/**
 * At least one sub-expression must hold (logical OR over the list).
 */
any?: Array<MatchExpr> | null, 
/**
 * No sub-expression may hold (logical NOR over the list).
 */
not?: Array<MatchExpr> | null, };

/**
 * Informational profile metadata; not used by matching or planning.
 */
export type Meta = { 
/**
 * Human-readable profile name (e.g. shown in the GUI's recent-profiles list).
 */
name?: string | null, 
/**
 * Prose note for humans reading the profile file; carried through
 * serialization but never interpreted or rendered by the tool.
 */
description?: string | null, };

/**
 * Output naming and collision handling (spec 4.8).
 */
export type OutputCfg = { 
/**
 * Output directory; profile default, usually overridden per run via
 * CLI/GUI run inputs (spec 3, 4.8).
 */
directory?: string | null, 
/**
 * `keep` (source basename, `.mkv` extension enforced) or a literal-mode
 * template (spec 4.7); defaults to `keep`.
 */
filename?: FilenameCfg, 
/**
 * Policy when the rendered output path already exists or two planned
 * outputs collide. An output path equal to any input path is always a
 * hard `SourceOverwrite` error regardless of this policy (spec 4.8, 5.2).
 */
on_collision?: CollisionPolicy, };

/**
 * The top-level profile document (spec 4): input matching, output naming,
 * track rules (in output order), and attachments/chapters/tags/title
 * configuration. Deserializes with `deny_unknown_fields` throughout: an
 * unrecognized key is a config error, not a silently ignored typo (spec 4:
 * "Unknown keys are errors, not warnings").
 */
export type Profile = { 
/**
 * Format version; must equal `1` in v1 (`UnsupportedProfileVersion` if
 * not). Incremented only on breaking format changes (spec 4).
 */
profile_version: number, 
/**
 * Optional descriptive metadata; purely informational, never
 * interpreted by matching or planning.
 */
meta?: Meta | null, 
/**
 * Primary-file matching rule and directory-walk options (spec 4.2).
 */
input: Input, 
/**
 * Output naming and collision policy (spec 4.8).
 */
output?: OutputCfg, 
/**
 * Track selection/change rules plus the unmatched-track policy
 * (spec 4.5). Restructured into a block so the policy lives with its
 * rules, matching `attachments` and `output`/`tags`.
 */
tracks: TracksCfg, 
/**
 * Attachment keep/drop/add rules (spec 4.9).
 */
attachments?: AttachmentsCfg, 
/**
 * Chapters handling: keep, drop, or an external locator (spec 4.9).
 */
chapters?: ChaptersCfg, 
/**
 * Global and per-track tag handling (spec 4.9).
 */
tags?: TagsCfg, 
/**
 * Output title handling: keep, clear, or a literal-mode template
 * (spec 4.9).
 */
title?: TitleCfg, };

/**
 * A scalar value inside `exact`/`changes` maps (spec 4.3/4.4).
 * `#[serde(untagged)]`: deserialization tries each variant in the order
 * declared below, so ordering is semantically load-bearing for numbers:
 * a plain numeric literal (`3`) matches `Int` before it ever reaches
 * `Float`, so only literals with a decimal point become `Float`. The
 * `Bool`-before-`Str` order is not load-bearing for typed YAML/JSON input
 * (a boolean node never deserializes as a string) but is kept explicit
 * for clarity.
 */
export type Scalar = boolean | number | number | string;

/**
 * `track.source` value: the primary file, or an external donor (spec 4.5).
 * `#[serde(untagged)]`, same variant-resolution rule as [`FilenameCfg`].
 */
export type SourceCfg = ExternalBlock | string;

/**
 * The closed grammar of suggestion edits (spec 5.3, D6); only ever narrows a
 * rule. Populated by the engine (see `suggest`) and accepted back from the
 * shell to apply (D43, D49).
 *
 * `AddExact`/`AddNotExact` carry a typed [`Scalar`], not a display string:
 * `exact` compares each property in its own domain (`core-72`), so the
 * variant is a core semantic. The engine holds the typed value when it builds
 * the edit; carrying it is what makes the applied delta identical to the
 * simulated one (`core-03`, D49).
 */
export type StructuredEdit = { "kind": "add_exact", 
/**
 * The matchable property to constrain.
 */
property: string, 
/**
 * The value to require, in the type the engine identified.
 */
value: Scalar, } | { "kind": "add_not_exact", 
/**
 * The matchable property to exclude on.
 */
property: string, 
/**
 * The value to exclude, in the type the engine identified.
 */
value: Scalar, } | { "kind": "add_substring", 
/**
 * The `track_name` substring to require.
 */
value: string, } | { "kind": "add_not_substring", 
/**
 * The `track_name` substring to exclude.
 */
value: string, };

/**
 * Global and per-track tag handling (spec 4.9), mapped to
 * `--no-global-tags`/`--no-track-tags`.
 */
export type TagsCfg = { 
/**
 * Global (container-level) tags: keep or drop. Defaults to `keep`.
 */
global?: KeepDrop, 
/**
 * Per-track tags: keep or drop. Defaults to `keep`.
 */
track?: KeepDrop, };

/**
 * Shared `{ template: ... }` block; a standalone struct (not an inline
 * enum variant) because serde ignores `deny_unknown_fields` on struct
 * variants of untagged enums.
 */
export type TemplateBlock = { 
/**
 * The template source text (spec 4.7); rendered in literal or regex
 * mode depending on where the block appears.
 */
template: string, };

/**
 * `title` value: keep, clear, or a literal-mode template (spec 4.9).
 * `#[serde(untagged)]`, same variant-resolution rule as the other
 * keyword-or-block enums above.
 */
export type TitleCfg = TemplateBlock | string;

/**
 * One track rule (spec 4.5): selects exactly one track (subject to
 * strict independent uniqueness, spec 2) and optionally applies property
 * changes to it.
 */
export type TrackRule = { 
/**
 * Where the rule resolves against: the primary file (default) or an
 * external donor located via a [`Locator`] (spec 4.5, 4.6).
 */
source?: SourceCfg, 
/**
 * The match expression a track of `source` must satisfy; serialized
 * under the profile key `match` (renamed here because `match` is a
 * Rust keyword).
 */
match: MatchExpr, 
/**
 * Tolerates zero matching tracks (spec 5.1). Two candidates on an
 * optional rule remain an `AmbiguousRule` error; `optional` covers
 * only the zero-candidate case, never widening uniqueness.
 */
optional?: boolean, 
/**
 * Settable-property changes to apply to the resolved track (spec 4.4
 * table); `None` leaves the track's properties untouched.
 */
changes?: { [key in string]: Scalar } | null, };

/**
 * Track handling: the unmatched-track policy plus the ordered rules
 * (spec 4.5). Parallel in shape to [`AttachmentsCfg`], but `unmatched`
 * defaults to `drop`: only rule-matched tracks survive unless the profile
 * opts into `keep` (spec 4.9 asymmetry note).
 */
export type TracksCfg = { 
/**
 * Policy for PRIMARY-file tracks no `rules` entry matches. Defaults to
 * `drop` (the declarative default). `keep` passes them through
 * untouched; consumed by `command` (Task 2). Donor tracks are
 * unaffected: a donor contributes only its rule-selected track.
 */
unmatched?: KeepDrop, 
/**
 * Ordered track rules; list order defines the output `--track-order`
 * (spec 4.5). Uniqueness-constrained (spec 2): each rule resolves to
 * exactly one track.
 */
rules: Array<TrackRule>, };
