// GENERATED FILE - do not edit.
// Regenerate: cargo run -p xtask -- gen-capability <schema.json> <this file>
// Source: mkvmerge identification output schema (facts only, not the schema).

use super::PropType;

pub static MATCHABLE_PROPERTIES: &[(&str, PropType)] = &[
    ("aac_is_sbr", PropType::String),
    ("alpha_mode", PropType::Integer),
    ("audio_bits_per_sample", PropType::Integer),
    ("audio_channels", PropType::Integer),
    ("audio_emphasis", PropType::Integer),
    ("audio_sampling_frequency", PropType::Integer),
    ("cb_subsample", PropType::String),
    ("chroma_siting", PropType::String),
    ("chroma_subsample", PropType::String),
    ("chromaticity_coordinates", PropType::String),
    ("codec", PropType::String),
    ("codec_delay", PropType::Integer),
    ("codec_id", PropType::String),
    ("codec_name", PropType::String),
    ("codec_private_data", PropType::String),
    ("codec_private_length", PropType::Integer),
    ("color_bits_per_channel", PropType::Integer),
    ("color_matrix_coefficients", PropType::Integer),
    ("color_primaries", PropType::Integer),
    ("color_range", PropType::Integer),
    ("color_transfer_characteristics", PropType::Integer),
    ("content_encoding_algorithms", PropType::String),
    ("default_duration", PropType::Integer),
    ("default_track", PropType::Boolean),
    ("display_dimensions", PropType::String),
    ("display_unit", PropType::Integer),
    ("enabled_track", PropType::Boolean),
    ("encoding", PropType::String),
    ("flag_commentary", PropType::Boolean),
    ("flag_hearing_impaired", PropType::Boolean),
    ("flag_original", PropType::Boolean),
    ("flag_text_descriptions", PropType::Boolean),
    ("flag_visual_impaired", PropType::Boolean),
    ("forced_track", PropType::Boolean),
    ("id", PropType::Integer),
    ("language", PropType::String),
    ("language_ietf", PropType::String),
    ("max_content_light", PropType::Integer),
    ("max_frame_light", PropType::Integer),
    ("max_luminance", PropType::Float),
    ("min_luminance", PropType::Float),
    ("minimum_timestamp", PropType::Integer),
    ("multiplexed_tracks", PropType::String),
    ("num_index_entries", PropType::Integer),
    ("number", PropType::Integer),
    ("packetizer", PropType::String),
    ("pixel_dimensions", PropType::String),
    ("program_number", PropType::Integer),
    ("projection_pose_pitch", PropType::Float),
    ("projection_pose_roll", PropType::Float),
    ("projection_pose_yaw", PropType::Float),
    ("projection_private", PropType::String),
    ("projection_type", PropType::Integer),
    ("stereo_mode", PropType::Integer),
    ("stream_id", PropType::Integer),
    ("sub_stream_id", PropType::Integer),
    ("teletext_page", PropType::Integer),
    ("text_subtitles", PropType::Boolean),
    ("track_name", PropType::String),
    ("type", PropType::String),
    ("uid", PropType::Integer),
    ("white_color_coordinates", PropType::String),
];
